### ISSUE TITLE
Always on capacitive touch LEDs

### ISSUE THREAD

**Issue by vanillagorillaa** [commaai/eon-neos-builder#17]
The LED's for the capacitive touch buttons are always on. Can probably save a tiny amount of power if we turn them off. Believe this was introduced with the unified kernel. User reported image below. 

Original Issue in EON-NEOS repo
https://github.com/commaai/eon-neos/issues/2

![image](https://user-images.githubusercontent.com/31773928/66173381-c459fc00-e604-11e9-817d-b87e250625f9.png)

**Comment by jyoung8607** [comment]
We need to take the LeEco backlight MPP config from here:

https://github.com/commaai/android_kernel_leeco_msm8996/blob/67704d384dc58535c4fe502f568ae2da707e1c1f/arch/arm/boot/dts/qcom/msm8996-le_zl1-evt.dtsi#L93-L115

And the OP3T backlight MPP config from I *think* here:

https://github.com/commaai/android_kernel_oneplus_msm8996/blob/25166c7ae1ecbc76d84cf0c941c20eb773540abb/arch/arm/boot/dts/qcom/msm-pmi8994.dtsi#L154-L165

And drop them into their respective places in the merged kernel, somewhere like [here](https://github.com/commaai/android_kernel_comma_msm8996/blob/master/arch/arm/boot/dts/qcom/msm8996pro-pmi8996-comma-leeco.dts) and [here](https://github.com/commaai/android_kernel_comma_msm8996/blob/master/arch/arm/boot/dts/qcom/msm8996pro-pmi8996-comma-oneplus.dts) respectively. Unfortunately the DTS tree from all three kernels are structured differently and all three have hilarious amounts of indirection and inheritance, so we'll have to see whether it just drops in.

Once the kernel knows which SOC multi-purpose pin controls the button backlight on each of the two boards, it will expose the controls in `/sys/class/leds/button-backlight`, and our pre-existing boot-time instruction to kill the backlight should start working again.

https://github.com/commaai/eon-neos-builder/blob/c358a3f01b714dc2d5166c09cd93548c3a4e6e49/devices/eon/ramdisk_common/comma.sh#L18-L19

If this drops in easily, I'll ship the fix with NEOS 15. If it puts up a fight, it'll have to wait until next time.

**Comment by jyoung8607** [comment]
It dropped in easily!

![20200529_101551](https://user-images.githubusercontent.com/46612682/83287492-a2664880-a196-11ea-821c-9bdbb13d850d.jpg)
