### ISSUE TITLE
missing simg2img

### ISSUE THREAD

**Issue by ed2k** [commaai/eon-neos-builder#3]
need to install android-tools-fsutils on ubuntu 16.04
and abootimg

**Comment by jfrux** [comment]
This isn't so much a bug, but more of a educational concern in the README I think.
I was thinking of adding Requirements section to the readme but I'm not sure, most people that do custom builds of Android already have a lot of this stuff anyway.

Not sure if it fits the target audience for this repo or not.

**Comment by ed2k** [comment]
it is, the build all script does install other packages

**Comment by jfrux** [comment]
Fair enough!
It was just something I thought of while I was doing it…
Just my two cents…

Not sure if it should be installing dependencies or not long term or anything.  Who knows.

**Comment by brubakerjeff** [comment]
@jfrux  are these the compilation instructions you are referring to for dependencies? Still working through this.

https://github.com/commaai/android/blob/master/README

**Comment by brubakerjeff** [comment]
@jfrux are these the instructions you could refer to? 
I see this originally comes from Cyanogen M13
https://web.archive.org/web/20161224194004/https://wiki.cyanogenmod.org/w/Doc:_manifests
Are the original build dependencies for Cyanogen M13 documented somewhere? Such as installing an Android SDK?

I'm running make and receive the following.
root@jeff-VirtualBox:~/Desktop/commaai/eon-neos-builder/mindroid/system# make
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=6.0.1
CM_VERSION=13.0-20181021-UNOFFICIAL-Sultan-oneplus3
TARGET_PRODUCT=cm_oneplus3
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
HOST_BUILD_TYPE=release
BUILD_ID=M4B30X
OUT_DIR=/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out
============================================
external/speex/Android.mk:55: TODOArm64: enable neon in libspeex
build/core/copy_headers.mk:15: warning: overriding recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/target/product/oneplus3/obj/include/qcom/display/copybit.h'
build/core/copy_headers.mk:15: warning: ignoring old recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/target/product/oneplus3/obj/include/qcom/display/copybit.h'
build/core/copy_headers.mk:15: warning: overriding recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/target/product/oneplus3/obj/include/qcom/display/copybit_priv.h'
build/core/copy_headers.mk:15: warning: ignoring old recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/target/product/oneplus3/obj/include/qcom/display/copybit_priv.h'
build/core/copy_headers.mk:15: warning: overriding recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/target/product/oneplus3/obj/include/qcom/display/c2d2.h'
build/core/copy_headers.mk:15: warning: ignoring old recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/target/product/oneplus3/obj/include/qcom/display/c2d2.h'
build/core/base_rules.mk:559: warning: overriding recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/target/product/oneplus3/root/res/images/charger/battery_fail.png'
build/core/base_rules.mk:559: warning: ignoring old recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/target/product/oneplus3/root/res/images/charger/battery_fail.png'
find: ‘dummy’: No such file or directory
ln: failed to create symbolic link 'libEGL_adreno.so': File exists
ln: failed to create symbolic link 'libEGL_adreno.so': File exists
**### No private recovery resources for TARGET_DEVICE oneplus3**
Lex: aidl <= frameworks/base/tools/aidl/aidl_language_l.l
flex-2.5.39: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
build/core/binary.mk:670: recipe for target '/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/host/linux-x86/obj/EXECUTABLES/aidl_intermediates/aidl_language_l.cpp' failed
make: *** [/home/jeff/Desktop/commaai/eon-neos-builder/mindroid/system/out/host/linux-x86/obj/EXECUTABLES/aidl_intermediates/aidl_language_l.cpp] Aborted (core dumped)

#### make failed to build some targets (01:47 (mm:ss)) ####

**Comment by pd0wm** [comment]
simg2img is added to the tools directory. Make sure to add the tools directory to your path if you don't have it globally installed.
